name: CI

on:
  push:
    branches:
    - "**"

  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        ruby: [ ruby-2.4, ruby-2.5, ruby-2.6 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - run: bundle exec rake
